export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

import R3F from '@/libs/R3F'
import GSAP from '@/libs/GSAP'
import Lenis from '@/libs/Lenis'

import '@/styles/app.scss'

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Lenis>
					<GSAP />
					{children}
					<R3F />
				</Lenis>
			</body>
		</html>
	)
}
