export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

import GSAP from '@/libs/GSAP'
import Lenis from '@/libs/Lenis'
import Cursor from '@/libs/Cursor'
import fontsClasses from '@/libs/Fonts'
import ScrollProgress from '@/components/ScrollProgress'
import Preloader from '@/components/Preloader'
import Header from '@/components/Header'

import '@/styles/app.scss'

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={fontsClasses}>
				<Lenis>
					<Preloader />
					<GSAP />
					<Header />
					<main>{children}</main>
					<ScrollProgress />
					<Cursor />
				</Lenis>
			</body>
		</html>
	)
}
